load("@smithy_rules//smithy:smithy.bzl", "smithy_library")
package(default_visibility = ["//visibility:public"])

smithy_library(
    name = "friendly_id_smithy_lib",
    srcs = ["trait-def.smithy"],
    config = "smithy-build.json",
    root_dir = "model",
)